version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: photoapp-sql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password123
      - MSSQL_PID=Express
    ports:
      - "1533:1433"
    volumes:
      - photoapp-db-data:/var/opt/mssql

  api:
    build:
      context: ./BE
      dockerfile: PhotoApp.Api/Dockerfile
    container_name: photoapp-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=PhotoApp;User Id=sa;Password=Your_strong_password123;Encrypt=False;TrustServerCertificate=True;"
      PhotoStorage__RootPath: "/app/storage/photos"
      AllowedHosts: "*"
    ports:
      - "5000:8080"
    volumes:
      - photos-storage:/app/storage

volumes:
  photoapp-db-data:
  photos-storage:
